import { LegalLayout, Section } from './LegalLayout'

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="January 1, 2025">
      <Section title="1. Acceptance of Terms">
        <p>By accessing or using Flashcards, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.</p>
      </Section>

      <Section title="2. Description of Service">
        <p>Flashcards is an AI-powered learning platform that allows users to generate, store, and review flashcard decks using spaced repetition. The service uses third-party AI providers to generate content.</p>
      </Section>

      <Section title="3. Account Registration">
        <p>You must create an account to use the service. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account.</p>
        <p>You must provide accurate information when creating your account. Accounts created with false information may be terminated.</p>
      </Section>

      <Section title="4. Acceptable Use">
        <p>You agree not to:</p>
        <ul className="list-disc list-inside flex flex-col gap-1 text-[var(--color-text-muted)]">
          <li>Use the service for any unlawful purpose</li>
          <li>Submit content that is harmful, offensive, or violates third-party rights</li>
          <li>Attempt to reverse engineer or circumvent the service</li>
          <li>Use automated tools to abuse the AI generation system</li>
          <li>Share access credentials with others</li>
          <li>Upload images containing personal data of third parties without consent</li>
        </ul>
      </Section>

      <Section title="5. AI-Generated Content">
        <p>Flashcard content is generated by third-party AI models. We do not guarantee the accuracy, completeness, or fitness for purpose of AI-generated content. You are responsible for reviewing generated cards before using them for study.</p>
        <p>Do not rely on AI-generated content for medical, legal, financial, or safety-critical decisions.</p>
      </Section>

      <Section title="6. Intellectual Property">
        <p>You retain ownership of content you create. By using the service, you grant us a limited license to store and process your content to provide the service.</p>
        <p>The Flashcards platform, including its design, code, and branding, is our intellectual property.</p>
      </Section>

      <Section title="7. Deck Sharing">
        <p>When you make a deck public, you grant any person with the share link the right to view its contents. You are responsible for ensuring shared content does not violate these terms or third-party rights.</p>
      </Section>

      <Section title="8. Termination">
        <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time.</p>
      </Section>

      <Section title="9. Disclaimer of Warranties">
        <p>The service is provided "as is" without warranties of any kind. We do not warrant that the service will be uninterrupted, error-free, or that AI-generated content will be accurate.</p>
      </Section>

      <Section title="10. Limitation of Liability">
        <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
      </Section>

      <Section title="11. Changes to Terms">
        <p>We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
      </Section>

      <Section title="12. Contact">
        <p>For questions about these terms: <span className="text-[var(--color-text-primary)]">legal@flashcards.app</span></p>
      </Section>
    </LegalLayout>
  )
}
